import "./globals.css";

import { Inter } from "next/font/google";

import { AuthProvider } from "@/components/AuthProvider";
import { SiteHeader } from "@/components/SiteHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next13 Blog Sample",
  description: "Generated by Cagil Seker",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <SiteHeader />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
